workloads_distribution:
  0Kb: 2
  1Kb: 24.79
  10Kb: 18.87
  100Kb: 17.87
  1Mb: 18.2
  10Mb: 16.7
  100Mb: 1.51
sessions_per_node_vm: 20
sessions_per_node_hw: 150

happy_path_duration_days: 30
degraded_path_durations_days: 7
nearfull_storage_percentage: 95
bucket_creation_healthy_mode: True
create_bucket_count: 50

#write,partial delete test cases.
write_percent_per_iter: 30
delete_percent_per_iter: 20
